[package]
name = "adder"
version = "1.0.0"
authors = [ "@RisaSoftStaking",]
edition = "2018"
publish = true

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.21.2"
features = ["cb_closure_managed_deser"]

[dev-dependencies.elrond-wasm-debug]
version = "0.21.2"
