[package]
name = "unlocker"
version = "0.0.0"
authors = [ "@RisaSoftStaking",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = [ "elrond-wasm-node",]

[dependencies.elrond-wasm]
version = "0.21.2"

[dev-dependencies.elrond-wasm-debug]
version = "0.21.2"

[dependencies.elrond-wasm-node]
version = "0.21.2"
optional = true