name: Builds and tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  wasm_test:
    name: Wasm tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: nightly
      - name: Install erdpy and arwentools
        run : |
          source .github/workflows/env
          pip3 install erdpy
          mkdir $HOME/elrondsdk
          erdpy config set dependencies.arwentools.tag v1.4.22
          erdpy deps install arwentools
  rust_test:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          default: true
          toolchain: nightly
      - name: Run rust tests
        run: cargo test
